# Generated by Django 5.1.6 on 2025-03-28 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_author_year_painting_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginNation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='painting',
            name='nation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.originnation'),
        ),
    ]
