# Generated by Django 5.1.6 on 2025-03-28 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_originnation_painting_nation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='painting',
            old_name='nation',
            new_name='origin_nation',
        ),
        migrations.AddField(
            model_name='painting',
            name='art_movement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.artmovement'),
        ),
        migrations.AddField(
            model_name='painting',
            name='technique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.technique'),
        ),
    ]
