# Generated by Django 5.1.6 on 2025-03-28 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_artmovement_technique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='author',
            old_name='year',
            new_name='death_year',
        ),
        migrations.AddField(
            model_name='author',
            name='profession',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='author',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.nationality'),
        ),
    ]
