# Generated by Django 5.1.7 on 2025-04-02 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_nationality_rename_year_author_death_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementPainting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.artmovement')),
                ('painting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.painting')),
            ],
        ),
    ]
